.PHONY: clean All

All:
	@echo "----------Building project:[ letter_pyramid - Debug ]----------"
	@cd "letter_pyramid" && "$(MAKE)" -f  "letter_pyramid.mk"
clean:
	@echo "----------Cleaning project:[ letter_pyramid - Debug ]----------"
	@cd "letter_pyramid" && "$(MAKE)" -f  "letter_pyramid.mk" clean
