.PHONY: clean All

All:
	@echo "----------Building project:[ SizeVariables - Debug ]----------"
	@cd "SizeVariables" && "$(MAKE)" -f  "SizeVariables.mk"
clean:
	@echo "----------Cleaning project:[ SizeVariables - Debug ]----------"
	@cd "SizeVariables" && "$(MAKE)" -f  "SizeVariables.mk" clean
