.PHONY: clean All

All:
	@echo "----------Building project:[ structure - Debug ]----------"
	@cd "structure" && "$(MAKE)" -f  "structure.mk"
clean:
	@echo "----------Cleaning project:[ structure - Debug ]----------"
	@cd "structure" && "$(MAKE)" -f  "structure.mk" clean
